name: flutter_google_places_api
description: This is dart implementation of google places api. Each requests returns corresponding response object. Google places api requires google api key. You can follow instruction in https://developers.google.com/places/web-service/get-api-key to get api key.
version: 0.0.12
homepage: https://github.com/bamnenim/flutter_google_places_api

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  equatable: ^1.1.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1